### ISSUE TITLE
About the language model

### ISSUE THREAD

**Issue by 1204271075** [sosuperic/MeanSum#1]
Hello , i have a question.  Is the language model provided for download generated by pretrain_lm.py ?

**Comment by sosuperic** [comment]
Yes that's right.

**Comment by doantumy** [comment]
Hi, I tried to train the language model but I got error `NameError: name 'Batch' is not defined`, Can you please help?

**Comment by sosuperic** [comment]
Oops! Added back the import Batch from models.nn_utils
