### ISSUE TITLE
Where can I get business.json?

### ISSUE THREAD

**Issue by nnnngo** [sosuperic/MeanSum#4]
I got an error which says 
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/yelp_dataset/business.json'
Where can I get business.json?

**Comment by sosuperic** [comment]
I just re-downloaded the dataset from https://www.yelp.com/dataset, and I see business.json in the unzipped files. Have you followed the steps in the "General Setup" section, as well as the steps in "Downloading data and pretrained models -- Data"? 

I've also noticed that depending on the version of the dataset (as of writing it's Round 13), Yelp sometimes names the files inconsistently (e.g. yelp_academic_dataset_review.json vs review.json). Perhaps check if that's the case?
